version: "3.9"

services:
  app:
    build: ./app
    container_name: ihomis-app
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./app/ihomis-plus:/var/www/html
      - ./app/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./app/bootstrap:/opt/bootstrap
      - ./ssl:/etc/apache2/ssl
      
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: ihomis-db
    ports:
      - "3357:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ihomisroot
      MYSQL_DATABASE: hospital_dbo
      MYSQL_USER: doh 
      MYSQL_PASSWORD: doh123456
    volumes:
      - ./db/data:/var/lib/mysql
    restart: unless-stopped
